# Generated by Django 6.0.1 on 2026-01-10 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailjet_api_key', models.CharField(help_text='Mailjet API Key', max_length=255)),
                ('mailjet_api_secret', models.CharField(help_text='Mailjet API Secret', max_length=255)),
                ('default_from_email', models.CharField(default='Dr. Abul Khayer (Biplob) <your-email@gmail.com>', help_text='Format: Name <email@domain.com>', max_length=255)),
                ('admin_email', models.EmailField(help_text='Admin notification email address', max_length=255)),
            ],
            options={
                'verbose_name': 'Mail Setting',
                'verbose_name_plural': 'Mail Setting',
            },
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='Appointment.availableslot')),
            ],
        ),
    ]
