# Generated by Django 6.0.1 on 2026-01-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.EmailField(max_length=255)),
                ('email_host_password', models.CharField(max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.CharField(default='Dr. Abul Khayer (Biplob) <your-email@gmail.com>', max_length=255)),
                ('admin_email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Mail Setting',
                'verbose_name_plural': 'Mail Setting',
            },
        ),
    ]
