# Generated by Django 6.0.1 on 2026-01-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_mailsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsetting',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
