# Generated by Django 6.0.1 on 2026-01-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_mailsetting_email_use_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsetting',
            name='email_backend',
            field=models.CharField(choices=[('smtp', 'SMTP (Gmail, Outlook, etc.)'), ('mailjet', 'Mailjet API')], default='smtp', help_text='Select email service provider', max_length=20),
        ),
        migrations.AddField(
            model_name='mailsetting',
            name='mailjet_api_key',
            field=models.CharField(blank=True, help_text='Mailjet API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='mailsetting',
            name='mailjet_api_secret',
            field=models.CharField(blank=True, help_text='Mailjet API Secret', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
    ]
