# Generated by Django 6.0.1 on 2026-01-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_add_email_backend_and_mailjet_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailsetting',
            name='email_backend',
        ),
        migrations.RemoveField(
            model_name='mailsetting',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='mailsetting',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='mailsetting',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='mailsetting',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='mailsetting',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='mailsetting',
            name='email_use_tls',
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='admin_email',
            field=models.EmailField(help_text='Admin notification email address', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='default_from_email',
            field=models.CharField(default='Dr. Abul Khayer (Biplob) <your-email@gmail.com>', help_text='Format: Name <email@domain.com>', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='mailjet_api_key',
            field=models.CharField(help_text='Mailjet API Key', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='mailjet_api_secret',
            field=models.CharField(help_text='Mailjet API Secret', max_length=255),
        ),
    ]
