# Generated by Django 6.0.1 on 2026-01-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0006_simplify_mailsetting_to_mailjet_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=10),
        ),
    ]
