# Generated by Django 6.0.1 on 2026-01-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0007_appointment_patient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_type',
        ),
    ]
