# Generated by Django 6.0.1 on 2026-01-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='About Me', max_length=100)),
                ('title', models.CharField(default='Professional Summary', max_length=200)),
                ('description_paragraph1', models.TextField()),
                ('description_paragraph2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/about/')),
                ('image_alt', models.CharField(default='Doctor with patient', max_length=200)),
                ('patients_managed', models.CharField(default='50+', max_length=50)),
                ('patients_managed_description', models.TextField(default='Successfully managed anaesthesia and critical care for thousands of patients.')),
                ('years_experience_detail', models.CharField(default='2+', max_length=50)),
                ('years_experience_description', models.TextField(default='Years of expertise in anaesthesiology, ICU management, and pain treatment.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Book Now', max_length=100)),
                ('title', models.CharField(default='Schedule a Virtual or In-Personal Appointment Today', max_length=300)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_alt', models.CharField(default='Doctor consultation', max_length=200)),
                ('show_virtual_consultations', models.BooleanField(default=True)),
                ('show_in_person_visits', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact/CTA Section',
                'verbose_name_plural': 'Contact/CTA Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Top Rated Specialist', max_length=100)),
                ('title_line1', models.CharField(default='Your Health,', max_length=200)),
                ('title_line2', models.CharField(default='Our Priority', max_length=200)),
                ('description', models.TextField(default='Expert care in Anaesthesiology, ICU, and Pain Management. Dedicated to providing compassionate tailored medical services.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/hero/')),
                ('image_alt', models.CharField(default='Dr. Abul Khayer', max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='Optional video URL for Watch Video button', null=True)),
                ('years_experience', models.CharField(default='12+', max_length=50)),
                ('patients_count', models.CharField(default='5k+', max_length=50)),
                ('emergency_availability', models.CharField(default='24/7', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('publication_info', models.CharField(help_text='e.g., Published in Journal of Oncology, 2024', max_length=300)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Research & Publications',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Font Awesome icon class (e.g., 'fas fa-syringe')", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in hero section services')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g., Surgical Patient, ICU Patient', max_length=200)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(default='05 MINS', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
