# Generated by Django 6.0.1 on 2026-01-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_icon', models.CharField(default='fas fa-stethoscope', max_length=50)),
                ('doctor_name', models.CharField(default='Dr. Abul Khayer (Biplob)', max_length=200)),
                ('description', models.TextField(default='Dedicated to providing expert anaesthesia, intensive care, pain management, and diabetology services with personalized treatment plans.')),
                ('address', models.CharField(default='Dhaka, Bangladesh', max_length=300)),
                ('phone_number', models.CharField(default='+8801762037234', max_length=20)),
                ('email', models.EmailField(default='akbiplob36@gmail.com', max_length=254)),
                ('working_hours', models.CharField(default='Mon - Fri: 9:00 AM - 6:00 PM', max_length=100)),
                ('quick_links_title', models.CharField(default='Quick Links', max_length=100)),
                ('quick_links', models.JSONField(default=list, help_text='List of quick links with label and href')),
                ('services_title', models.CharField(default='Our Services', max_length=100)),
                ('services_links', models.JSONField(default=list, help_text='List of service links')),
                ('resources_title', models.CharField(default='Patient Resources', max_length=100)),
                ('resources_links', models.JSONField(default=list, help_text='List of resource links')),
                ('social_media_title', models.CharField(default='Follow Us', max_length=100)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(default='Copyright © 2025 Dr. Abul Khayer (Biplob). All rights reserved.', max_length=300)),
                ('footer_links', models.JSONField(default=list, help_text='List of footer bottom links (Privacy Policy, Terms, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_icon', models.CharField(default='fas fa-stethoscope', help_text='Font Awesome icon class', max_length=50)),
                ('doctor_name', models.CharField(default='Dr. Abul Khayer (Biplob)', max_length=200)),
                ('doctor_title', models.CharField(default='Anaesthetist, Intensivist & Pain Physician', max_length=200)),
                ('phone_number', models.CharField(default='+8801762037234', max_length=20)),
                ('email', models.EmailField(default='akbiplob36@gmail.com', max_length=254)),
                ('working_hours', models.CharField(default='Mon - Fri: 9:00 AM - 6:00 PM', max_length=100)),
                ('menu_items', models.JSONField(default=list, help_text='List of menu items with label and href')),
                ('appointment_button_text', models.CharField(default='Book Appointment', max_length=100)),
                ('appointment_button_icon', models.CharField(default='fas fa-calendar-check', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navbar Settings',
                'verbose_name_plural': 'Navbar Settings',
            },
        ),
    ]
