# Generated by Django 6.0.1 on 2026-01-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Dr. Abul Khayer (Biplob)', max_length=200)),
                ('favicon', models.ImageField(blank=True, help_text='Upload favicon (recommended: 32x32 or 16x16 PNG/ICO)', null=True, upload_to='site/favicon/')),
                ('favicon_url', models.URLField(blank=True, help_text='Or provide favicon URL instead', null=True)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='contactsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', null=True, upload_to='portfolio/contact/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload profile image', null=True, upload_to='portfolio/testimonials/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload thumbnail image', null=True, upload_to='portfolio/videos/'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL instead', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL instead', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Or provide thumbnail URL instead', null=True),
        ),
    ]
