# Generated by Django 6.0.1 on 2026-01-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_sitesettings_contactsection_image_testimonial_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='favicon_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
    ]
