# Generated by Django 6.0.1 on 2026-01-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_remove_contactsection_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='✦ Specialized Care', max_length=100)),
                ('title', models.CharField(default='Specialized Medical Services', max_length=300)),
                ('description', models.TextField(default='Delivering evidence-based treatment with compassion and clinical excellence.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Section',
            },
        ),
    ]
