# Generated by Django 6.0.1 on 2026-01-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_servicessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Font Awesome icon class (e.g., 'fas fa-syringe')", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Portfolio.servicessection')),
            ],
            options={
                'verbose_name': 'Services Section Item',
                'verbose_name_plural': 'Services Section Items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
