# Generated by Django 6.0.1 on 2026-01-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_servicessectionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Educational Videos', max_length=100)),
                ('title', models.CharField(default='Watch: My Promise to You', max_length=300)),
                ('show_all_videos_link', models.URLField(blank=True, help_text="Link for 'Show All Videos' button (e.g., YouTube channel, external page, or /#blog for same page)", null=True)),
                ('show_all_videos_text', models.CharField(default='Show All Videos', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Section Settings',
                'verbose_name_plural': 'Video Section Settings',
            },
        ),
    ]
