# Generated by Django 6.0.1 on 2026-01-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_videosectionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='developed_by_text',
            field=models.CharField(default='developed by', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer1_name',
            field=models.CharField(default='queio', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer1_url',
            field=models.URLField(default='https://queio.com/'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer2_name',
            field=models.CharField(default='shaznuz', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer2_url',
            field=models.URLField(default='https://shaznuz.com/'),
        ),
    ]
