# Generated by Django 6.0.1 on 2026-01-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_footersettings_developed_by_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='developed_by_text',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='developer1_name',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='developer1_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='developer2_name',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='developer2_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='footer_links',
        ),
    ]
