# Generated by Django 6.0.1 on 2026-01-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_remove_footersettings_developed_by_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='quick_links',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='quick_links_title',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='resources_links',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='resources_title',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='services_links',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='services_title',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_sections',
            field=models.JSONField(default=list, help_text="List of footer sections with title and links. Format: [{'title': 'Section Title', 'links': [{'label': 'Link Title', 'href': '/link'}]}]"),
        ),
    ]
