# Generated by Django 6.0.1 on 2026-01-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_remove_footersettings_quick_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarsettings',
            name='menu_items',
        ),
    ]
